VIRTUAL_WIDTH = 384
VIRTUAL_HEIGHT = 216

WINDOW_WIDTH = 1280
WINDOW_HEIGHT = 720
TILE_SIZE = 16

--
-- entity constants
--
PLAYER_WALK_SPEED = 60
PLAYER_THROW_DISTANCE = 4 * TILE_SIZE

MAP_WIDTH = VIRTUAL_WIDTH / TILE_SIZE - 2
MAP_HEIGHT = math.floor(VIRTUAL_HEIGHT / TILE_SIZE) - 2

MAP_RENDER_OFFSET_X = (VIRTUAL_WIDTH - (MAP_WIDTH * TILE_SIZE)) / 2
MAP_RENDER_OFFSET_Y = (VIRTUAL_HEIGHT - (MAP_HEIGHT * TILE_SIZE)) / 2


MAP_BOTTOM_EDGE = VIRTUAL_HEIGHT - (VIRTUAL_HEIGHT - MAP_HEIGHT * TILE_SIZE)
					+ MAP_RENDER_OFFSET_Y - TILE_SIZE
MAP_TOP_EDGE = MAP_RENDER_OFFSET_Y + TILE_SIZE
MAP_RIGHT_EDGE = VIRTUAL_WIDTH - TILE_SIZE * 2
MAP_LEFT_EDGE = MAP_RENDER_OFFSET_X + TILE_SIZE
--
-- tile IDs
--
TILE_TOP_LEFT_CORNER = 4
TILE_TOP_RIGHT_CORNER = 5
TILE_BOTTOM_LEFT_CORNER = 23
TILE_BOTTOM_RIGHT_CORNER = 24

TILE_EMPTY = 19

TILE_FLOORS = {
    7, 8, 9, 10, 11, 12, 13,
    26, 27, 28, 29, 30, 31, 32,
    45, 46, 47, 48, 49, 50, 51,
    64, 65, 66, 67, 68, 69, 70,
    88, 89, 107, 108
}

TILE_TOP_WALLS = {58}
TILE_BOTTOM_WALLS = {79}
TILE_LEFT_WALLS = {77}
TILE_RIGHT_WALLS = {78}